[analysis]
  line_keyword = [
    "TESTCASE PASS!",
    "TESTCASE FAILED!",
    "different at pc",
    "Error-[FGP_AFFINITY_FAILED] cpu_affinity/auto_affinity failed",
  ]
  analysis_res = [
    "pass",
    "self check failed",
    "difftest failed",
    "core isn't enough"
  ]

[result]
  file = "./res.txt"