[config]
simulator = "vcs"

# all or part
# all: all test
# part: part_list test
sim_mode = "part"
sim_num = 8

part_list = [
]

case_prefix = "case" #modified point
case_abs_path = "NOOP_HOME/regression" #modified point
sim_path = "NOOP_HOME/sim" #modified point

[case]
  list = [
    "xxx"
  ]
